name: sg-environment
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - matplotlib
  - requests
  - beautifulsoup4
  - google-api-python-client
  - oauth2client
  - appmode
  - ipywidgets
  - jupyter_contrib_nbextensions

